### ISSUE TITLE
RustR error

### ISSUE THREAD

**Issue by conikeec** [rustr/rustr#1]
Followed suggested installation steps in book (on OSX El Capitan)

Executed Sample code in RStudio and noticed this error message
Am I missing any other step

> library(rustinr)
> rust(code ='
+ // #[rustr_export]
+      pub fn say_hi() -> String{
+      "Hello World".into()
+      }
+      ')
Error in system(cmd, intern = !getOption("verbose")) : 
  error in running command
>

**Comment by qinwf** [comment]
Hi, thanks for your report. Please provide more info about the steps.  Please run these scripts and see the result:

```r
# show more info for rustr
options(verbose = TRUE)
library(rustinr)

rust(code ='
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

# find cargo
system("which cargo")

# check rustc version
system("rustc --version")

system("cargo --version")

# R session info
sessionInfo()

# check loaded dlls
getLoadedDLLs()

# Rust temporary  source 
SOURCE_RUST_PATH$obj

# Rust build result
list.files(file.path(SOURCE_RUST_PATH$obj,"src/rustlib/target/release"))

# check lib.rs
cat(readLines(file.path(SOURCE_RUST_PATH$obj,"src/rustlib/src/lib.rs")),sep="\n")

# R build result
list.files(file.path(SOURCE_RUST_PATH$obj,"src/"))
```

**Comment by qinwf** [comment]
On my PC:
```
> # show more info for rustr
> options(verbose = TRUE)

> library(rustinr)

> 
> rust(code ='
+      // #[rustr_export]
+      pub fn say_hi() -> String{
+      "Hello World".into()
+      }
+      ')
tempfile : C:\Users\outwen\AppData\Local\Temp\Rtmp04xdMw\filebe8bc11377.rs
def : pub fn say_hi() -> String
parameter : 
[1] ""


funcion information :
$name
[1] "say_hi"

$param
character(0)

$type
character(0)

$ret
[1] "TRUE"

$rettype
[1] "String"

$roxchunk
character(0)


#[no_mangle]
pub extern "C" fn rustr_say_hi()->SEXP{

  let res  = say_hi();

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}
   Compiling rustlib v0.1.0 (file:///C:/Users/outwen/AppData/Local/Temp/Rtmp04xdMw/qxJFNNnLVpqF/src/rustlib)
note: link against the following native artifacts when linking against this static library
note: the order and any duplication can be significant on some platforms, and so may need to be preserved
note: library: R
note: library: R
note: library: gcc_eh
note: library: ws2_32
note: library: userenv
note: library: shell32
note: library: advapi32
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.0BE/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c REXPORT.c -o REXPORT.o
C:\Rtools\mingw_64\bin\nm.exe: rust.metadata.bin: File format not recognized
C:\Rtools\mingw_64\bin\nm.exe: rustlib.0.bytecode.deflate: File format not recognized
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o KvzARrFRYMqY.dll tmp.def REXPORT.o -Lrustlib/target/release/ -lrustlib -lws2_32 -luserenv -lshell32 -ladvapi32 -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.0BE/bin/x64 -lR
'envir' chosen:<environment: R_GlobalEnv>
encoding = "native.enc" chosen
--> parsed 1 expressions; now eval(.)ing them:

>>>> eval(expression_nr. 1 )
		 =================

> say_hi = function(){ .Call('KvzARrFRYMqY_say_hi',PACKAGE = 'KvzARrFRYMqY')}
curr.fun: symbol =
 .. after ‘expression(say_hi = function(){ .Call('KvzARrFRYMqY_say_hi',PACKAGE = 'KvzARrFRYMqY')})’
> 
> # find cargo
> system("which cargo")
/c/Users/outwen/.cargo/bin/cargo
> 
> # check rustc version
> system("rustc --version")
rustc 1.10.0-nightly (2174bd97c 2016-04-14)
> 
> system("cargo --version")
cargo 0.11.0-nightly (59238e8 2016-04-14)
> 
> # R session info
> sessionInfo()
R version 3.3.0 beta (2016-04-14 r70486)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rustinr_0.1.0

loaded via a namespace (and not attached):
[1] tools_3.3.0
> 
> # check loaded dlls
> getLoadedDLLs()
                                                                                    Filename
base                                                                                    base
methods                  C:/Program Files/R/R-3.3.0beta/library/methods/libs/x64/methods.dll
utils                        C:/Program Files/R/R-3.3.0beta/library/utils/libs/x64/utils.dll
grDevices            C:/Program Files/R/R-3.3.0beta/library/grDevices/libs/x64/grDevices.dll
graphics               C:/Program Files/R/R-3.3.0beta/library/graphics/libs/x64/graphics.dll
stats                        C:/Program Files/R/R-3.3.0beta/library/stats/libs/x64/stats.dll
tools                        C:/Program Files/R/R-3.3.0beta/library/tools/libs/x64/tools.dll
internet                                   C:/PROGRA~1/R/R-33~1.0BE/modules/x64/internet.dll
(embedding)                                                                      (embedding)
qxJFNNnLVpqF C:/Users/outwen/AppData/Local/Temp/Rtmp04xdMw/qxJFNNnLVpqF/src/qxJFNNnLVpqF.dll
tdMNnEwPFFDB C:/Users/outwen/AppData/Local/Temp/Rtmp04xdMw/qxJFNNnLVpqF/src/tdMNnEwPFFDB.dll
KvzARrFRYMqY C:/Users/outwen/AppData/Local/Temp/Rtmp04xdMw/qxJFNNnLVpqF/src/KvzARrFRYMqY.dll
             Dynamic.Lookup
base                  FALSE
methods               FALSE
utils                 FALSE
grDevices             FALSE
graphics              FALSE
stats                 FALSE
tools                 FALSE
internet               TRUE
(embedding)           FALSE
qxJFNNnLVpqF           TRUE
tdMNnEwPFFDB           TRUE
KvzARrFRYMqY           TRUE
> 
> # Rust temporary  source 
> SOURCE_RUST_PATH$obj
[1] "C:\\Users\\outwen\\AppData\\Local\\Temp\\Rtmp04xdMw\\qxJFNNnLVpqF"
> 
> # Rust build result
> list.files(file.path(SOURCE_RUST_PATH$obj,"src/rustlib/target/release"))
[1] "build"           "deps"            "examples"        "librustlib.a"   
[5] "librustlib.rlib" "native"         
> 
> # check lib.rs
> cat(readLines(file.path(SOURCE_RUST_PATH$obj,"src/rustlib/src/lib.rs")),sep="\n")
#[macro_use]
extern crate rustr;
pub mod export;
pub use rustr::*;

     // #[rustr_export]
     pub fn say_hi() -> String{
     "Hello World".into()
     }
     
> 
> # R build result
> list.files(file.path(SOURCE_RUST_PATH$obj,"src/"))
[1] "KvzARrFRYMqY.dll" "Makevars"         "qxJFNNnLVpqF.dll"
[4] "REXPORT.c"        "REXPORT.o"        "rustlib"         
[7] "tdMNnEwPFFDB.dll"
```

**Comment by qinwf** [comment]
I update `rustinr` package with a new `check_rustr()` function.

```r
library(rustinr)
check_rustr() # or check_rustr(detail = TRUE)
```

```r
Running:
library(rustinr)

Running:
rust(code = '
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

Great! It works!
```

```r
Sys.setenv(PATH="")
check_rustr()
```

```
Running:
library(rustinr)

Running:
rust(code = '
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

 Error in system(cmd, intern = !getOption("verbose")) : 'cargo' not found 
Something is not working correctly. Let's read more detail.

Running:
library(rustinr)

Running:
rust(code = '
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

tempfile : C:\Users\outwen\AppData\Local\Temp\RtmpWkDZn8\file58871a2167b.rs
def : pub fn say_hi() -> String
parameter : 
[1] ""


funcion information :
$name
[1] "say_hi"

$param
character(0)

$type
character(0)

$ret
[1] "TRUE"

$rettype
[1] "String"

$roxchunk
character(0)


#[no_mangle]
pub extern "C" fn rustr_say_hi()->SEXP{

  let res  = say_hi();

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.0BE/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c REXPORT.c -o REXPORT.o
cd rustlib && cargo build --release
cargo: not found
make: *** [rustlib/target/release/librustlib.rlib] Error 127
Warning message:
running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-33~1.0BE/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.0BE/share/make/winshlib.mk" SHLIB="ONLVTkGgDjVt.dll" PKG_LIBS='-Lrustlib/target/release/ -lrustlib -lws2_32 -luserenv -lshell32 -ladvapi32' WIN=64 TCLBIN=64 OBJECTS="REXPORT.o"' had status 2 
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/outwen/AppData/Local/Temp/RtmpWkDZn8/afQRXigmodfe/src/ONLVTkGgDjVt.dll':
  LoadLibrary failure:  找不到指定的模块。

In addition: Warning message:
In library(rustinr) : package ‘rustinr’ already present in search()

Find cargo:
cargo is not in PATH

Find CARGO_HOME:
CARGO_HOME is not set.

sessionInfo:

R version 3.3.0 beta (2016-04-14 r70486)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rustinr_0.1.0

loaded via a namespace (and not attached):
[1] tools_3.3.0


Loaded DLLs:

                                                                                    Filename
base                                                                                    base
methods                  C:/Program Files/R/R-3.3.0beta/library/methods/libs/x64/methods.dll
utils                        C:/Program Files/R/R-3.3.0beta/library/utils/libs/x64/utils.dll
grDevices            C:/Program Files/R/R-3.3.0beta/library/grDevices/libs/x64/grDevices.dll
graphics               C:/Program Files/R/R-3.3.0beta/library/graphics/libs/x64/graphics.dll
stats                        C:/Program Files/R/R-3.3.0beta/library/stats/libs/x64/stats.dll
tools                        C:/Program Files/R/R-3.3.0beta/library/tools/libs/x64/tools.dll
internet                                   C:/PROGRA~1/R/R-33~1.0BE/modules/x64/internet.dll
(embedding)                                                                      (embedding)
afQRXigmodfe C:/Users/outwen/AppData/Local/Temp/RtmpWkDZn8/afQRXigmodfe/src/afQRXigmodfe.dll
             Dynamic.Lookup
base                  FALSE
methods               FALSE
utils                 FALSE
grDevices             FALSE
graphics              FALSE
stats                 FALSE
tools                 FALSE
internet               TRUE
(embedding)           FALSE
afQRXigmodfe           TRUE


Rust temporary source:
C:\Users\outwen\AppData\Local\Temp\RtmpWkDZn8\afQRXigmodfe


Rust build result:
[1] "build"           "deps"            "examples"        "librustlib.a"   
[5] "librustlib.rlib" "native"         


Check lib.rs:
#[macro_use]
extern crate rustr;
pub mod export;
pub use rustr::*;

             // #[rustr_export]
             pub fn say_hi() -> String{
             "Hello World".into()
             }
             


R build result
[1] "afQRXigmodfe.dll" "Makevars"         "REXPORT.c"       
[4] "REXPORT.o"        "rustlib"         


Something is not working correctly. rustr is not ready.
```

**Comment by conikeec** [comment]
On executing checkrustr (rstudio, zsh, osx el capitan)

> check_rustr(detail = T)
Running:
library(rustinr)

Running:
rust(code = '
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

tempfile : /private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/file7b706e8a1874.rs
def : pub fn say_hi() -> String
parameter : 
[1] ""


funcion information :
$name
[1] "say_hi"

$param
character(0)

$type
character(0)

$ret
[1] "TRUE"

$rettype
[1] "String"

$roxchunk
character(0)


#[no_mangle]
pub extern "C" fn rustr_say_hi()->SEXP{

  let res  = say_hi();

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}
sh: cargo: command not found
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c REXPORT.c -o REXPORT.o
cd rustlib && cargo build --release
/bin/sh: cargo: command not found
make: *** [rustlib/target/release/librustlib.rlib] Error 127
Error in dyn.load(file.path(paste0(rss2, .Platform$dynlib.ext))) : 
  unable to load shared object '/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/HicWUAbPezAI/src/vbvvPdwNdMxT.so':
  dlopen(/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/HicWUAbPezAI/src/vbvvPdwNdMxT.so, 6): image not found
In addition: Warning message:
In library(rustinr) : package ‘rustinr’ already present in search()

Something is not working correctly. Let's read more detail.

Running:
library(rustinr)

Running:
rust(code = '
// #[rustr_export]
pub fn say_hi() -> String{
    "Hello World".into()
}
')

tempfile : /private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/file7b702c4ba05e.rs
def : pub fn say_hi() -> String
parameter : 
[1] ""


funcion information :
$name
[1] "say_hi"

$param
character(0)

$type
character(0)

$ret
[1] "TRUE"

$rettype
[1] "String"

$roxchunk
character(0)


#[no_mangle]
pub extern "C" fn rustr_say_hi()->SEXP{

  let res  = say_hi();

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}
sh: cargo: command not found
cd rustlib && cargo build --release
/bin/sh: cargo: command not found
make: *** [rustlib/target/release/librustlib.rlib] Error 127
Error in dyn.load(file.path(paste0(rss2, .Platform$dynlib.ext))) : 
  unable to load shared object '/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/HicWUAbPezAI/src/KHgfnFpZYBta.so':
  dlopen(/private/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T/RtmprKuFmB/HicWUAbPezAI/src/KHgfnFpZYBta.so, 6): image not found
In addition: Warning message:
In library(rustinr) : package ‘rustinr’ already present in search()

Find cargo:
cargo is not in PATH

Find CARGO_HOME:
CARGO_HOME is not set.

sessionInfo:

R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rustinr_0.1.0

loaded via a namespace (and not attached):
[1] httr_1.1.0      R6_2.1.2        tools_3.2.4     withr_1.0.1    
[5] curl_0.9.7      memoise_1.0.0   git2r_0.14.0    digest_0.6.9   
[9] devtools_1.11.1


Loaded DLLs:

                                                                                              Filename
base                                                                                              base
utils               /Library/Frameworks/R.framework/Versions/3.2/Resources/library/utils/libs/utils.so
methods         /Library/Frameworks/R.framework/Versions/3.2/Resources/library/methods/libs/methods.so
grDevices   /Library/Frameworks/R.framework/Versions/3.2/Resources/library/grDevices/libs/grDevices.so
graphics      /Library/Frameworks/R.framework/Versions/3.2/Resources/library/graphics/libs/graphics.so
stats               /Library/Frameworks/R.framework/Versions/3.2/Resources/library/stats/libs/stats.so
tools               /Library/Frameworks/R.framework/Versions/3.2/Resources/library/tools/libs/tools.so
internet                                /Library/Frameworks/R.framework/Resources/modules//internet.so
(embedding)                                                                                (embedding)
digest            /Library/Frameworks/R.framework/Versions/3.2/Resources/library/digest/libs/digest.so
devtools      /Library/Frameworks/R.framework/Versions/3.2/Resources/library/devtools/libs/devtools.so
git2r               /Library/Frameworks/R.framework/Versions/3.2/Resources/library/git2r/libs/git2r.so
curl                  /Library/Frameworks/R.framework/Versions/3.2/Resources/library/curl/libs/curl.so
            Dynamic.Lookup
base                 FALSE
utils                FALSE
methods              FALSE
grDevices            FALSE
graphics             FALSE
stats                FALSE
tools                FALSE
internet              TRUE
(embedding)          FALSE
digest                TRUE
devtools              TRUE
git2r                 TRUE
curl                  TRUE


Rust temporary source:
/var/folders/f9/23439cns7gn9g81r46tp2g4w0000gn/T//RtmprKuFmB/HicWUAbPezAI


Rust build result:
character(0)


Check lib.rs:
#[macro_use]
extern crate rustr;
pub mod export;
pub use rustr::*;

             // #[rustr_export]
             pub fn say_hi() -> String{
             "Hello World".into()
             }
             


R build result
[1] "Makevars"  "REXPORT.c" "REXPORT.o" "rustlib"  


Something is not working correctly. rustr is not ready.

**Comment by qinwf** [comment]
```cmd
Find cargo:
cargo is not in PATH

Find CARGO_HOME:
CARGO_HOME is not set.
```

`cargo` is not in your PATH. Maybe Rust was not correctly installed.

**Comment by conikeec** [comment]
Used rustup to install 

Refer : https://gist.github.com/conikeec/e4303c8237e65b58ca950b2c5dc8d909

 ~ > which cargo
/Users/XXX/.local/bin/cargo
 ~ > echo $CARGO_HOME
/Users/XXX/.cargo

**Comment by qinwf** [comment]
Did you get Rust and R ready?

I should be more explicit on the book. 

We can put cargo in PATH, or set CARGO_HOME variable to the cargo binary.

http://book.rustr.org/mac.html

origin:
> You can put Rust installation in path or set CARGO_HOME environment variable to the path of cargo.


This also make me think about changing CARGO_HOME to CARGO_BIN, before putting `rustinr` R package on CRAN. It is used in [Makevars](https://github.com/rustr/rustinr/blob/master/inst/init/Makevars) to help R to find Rust compiler.

**Comment by conikeec** [comment]
I finally resolved the problem.
Let me push a PR to fix the book documentation and I am sure anyone with RStudio on OSX will encounter this issue

**Comment by conikeec** [comment]
Closing the PR.
This issue is targeted towards those who are using RStudio 

I am issuing a PR to the book repository to amend the installation chapter 

Those using [RStudio](https://www.rstudio.com/), follow steps as indicated below
1.Download the [distribution](https://www.rstudio.com/products/rstudio/download) based on your operating system 
2.Note that RStudio can be launched from Finder/Doc or command line
3.On launching RStudio from Finder you will notice that it will not get it's environment from ~/.bashrc or ~/.zshrc. Instead, it will get it's environment variables from system-wide settings. To verify, launch RStudio from Finder and type ```system(echo $PATH)```. Then compare by typing ```echo $PATH``` in your terminal. 
3.In order to mitigate this, create a start-up initialization script to load your environment variables as configured in ~/.bashrc or ~/.zshrc
  ```touch ~/.Renviron | R_PATH="PATH=$PATH" | echo $R_PATH >  ~/.Renviron```
4.Restart RStudio and verify again by typing ```system(echo $PATH)``` at command prompt.
