### ISSUE TITLE
Problem in R CMD INSTALL mypac.tar.gz

### ISSUE THREAD

**Issue by ravinder387** [rustr/rustr#14]
C:\Users\ravin\Downloads>R CMD INSTALL mypac_1.0.tar.gz
In R CMD INSTALL
* installing to library 'C:/Users/ravin/OneDrive/Documents/R/win-library/3.5'
* installing *source* package 'mypac' ...
** libs
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c REXPORT.c -o REXPORT.o
cd rustlib && cargo build --release --target i686-pc-windows-gnu
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustr v0.1.9
error[E0463]: can't find crate for `std`
  |
  = note: the `i686-pc-windows-gnu` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rustr`.

To learn more, run the command again with --verbose.
make: *** [Makevars.win:23: rustlib/target/i686-pc-windows-gnu/release/librustlib.rlib] Error 101
ERROR: compilation failed for package 'mypac'
* removing 'C:/Users/ravin/OneDrive/Documents/R/win-library/3.5/mypac'

**Comment by qinwf** [comment]
https://rustr.github.io/book/windows.html#get-rust-with-gnu-abi

If you want to build multi-arch R package, make sure you install both 64bit and 32bit Rust standard library, for example `C:\Rust\lib\rustlib\i686-pc-windows-gnu` and `C:\Rust\lib\rustlib\x86_64-pc-windows-gnu`
