### ISSUE TITLE
Could you add a license to this code so others can use it?

### ISSUE THREAD

**Issue by clauswilke** [rustr/rustr#17]
It looks like this repository is not being updated anymore. Could you clarify under what license the code is published, so somebody else could take the code and use it as the basis for their efforts in R rust integration?

**Comment by clauswilke** [comment]
Oh, I see, it's in the Cargo.toml file, so maybe that's sufficient. I was looking for a `LICENSE` file.

**Comment by qinwf** [comment]
Yes, it is Apache-2.0. https://github.com/rustr/rustr/blob/master/Cargo.toml
