### ISSUE TITLE
Cargo/rustc location improvements

### ISSUE THREAD

**Issue by scottmmjackson** [rustr/rustr#4]
Is there a way you want to approach possibly injecting the cargo path at runtime? Or is that something you plan on supporting?

It'd be an issue of code portability- being able to locate cargo on some servers might be a little more complex. Thoughts?

**Comment by qinwf** [comment]
Yes. See https://book.rustr.org/linux.html#get-rust-1

```
You can put Rust installation in path or set CARGO_HOME environment variable to the path of cargo binary.
```

**Comment by scottmmjackson** [comment]
Hmm, I guess what I'm asking is if I don't want to touch the environment variables (or if I want to override them), is that something you plan to support?

**Comment by qinwf** [comment]
Yes, CARGO_HOME is used in Makevar and Makevar.win file.

see https://github.com/rustr/rustr/blob/master/rtest/src/Makevars.win

Just change the auto generated Makevars file by rustinr.

**Comment by scottmmjackson** [comment]
Makes sense, I'll close this.
