### ISSUE TITLE
Using default values

### ISSUE THREAD

**Issue by dodomorandi** [rustr/rustr#9]
It would be very nice if it could be possible to _automagically_ set default values for function parameters.

**Comment by scottmmjackson** [comment]
Could you give an example of the behavior you're looking for?

**Comment by dodomorandi** [comment]
I wanted to port some functions from native R to Rust. The problem is that some of these have default parameter values in their signature, something like:

    fun <- function(arg1, arg2, arg3=3, arg4=4.8) {
    /* ... */
    }

If I am not wrong, it is not possible to create this function with rustr, and it is quite unfortunate.

I don't know if it would be a good idea to have a similar syntax in Rust (at to date, we do not have _default parameter value_ syntax), but probably it could be nice if `Option<_>` could be taken as parameter. In this way the default value would be set inside the function whenever a `None` is matched. This is just a rough idea, what do you think about it?

**Comment by dodomorandi** [comment]
Ok, thanks. Definitely wrong place to ask ;)
